[package]
name = "middleware-rust"
version = "0.1.0"
authors = ["Brandur <brandur@mutelight.org>"]

[dependencies]
futures = "*"
env_logger = "0.5"
actix = "0.4"
actix-web = "0.3"
slog = "*"
slog-async = "*"
slog-term = "*"
uuid = { version = "0.5", features = ["v4"] }
